### PR TITLE
Generic update

### PR DESCRIPTION
**Pull request by f1erro**

### CODE REVIEW

**Comment by alexkhimich** [comment]
Build failed

**Comment by alexkhimich** [comment]
Now go complains `[SLOW TEST:10.030 seconds]` :( for many tests. Is it related to db copy?

**Comment by f1erro** [comment]
Maybe? But it should take very long to copy over a few KB...

**Comment by f1erro** [comment]
Should not**

**Comment by alexkhimich** [comment]
Hey, `UPDATE api_product SET _change_selector=$1, api_resources=$2, environments=$3, id=$4, tenant_id=$5 WHERE created_at=$6 AND id=$7 AND tenant_id=$8 AND updated_at=$9` This is wrong update statement :) i saw in the logs some tests fail

**Comment by f1erro** [comment]
show me the logs I will believe it when I see it

**Comment by sramamoorthy73** [comment]
Not directly related, but I was mentioning this to Mitch yesterday. Delete/Insert is much more performant than Update - Especially since 
(1) the number of columns in our tables are big
(2) Transicator does row level changes & not field level (that is you have to update the entire row).

**Comment by f1erro** [comment]
Not sure about that
http://stackoverflow.com/questions/1271641/in-sql-is-update-always-faster-than-deleteinsert

**Comment by sramamoorthy73** [comment]
Once you are done with the update, it will be easy to run some metric and compare.

**Comment by sramamoorthy73** [comment]
It is a very complicated topic with so many factors coming in to play. Had our updates been column specific - its a no brainer to just do updates.

**Pull request closed without merging**
